OS-ABC/HelloWorld

doc/Start/images/README.md
=> add images

doc/HomeWork/1901210420.md
This is my first homework, PTAL.
=> lcy: first pr

doc/HomeWork/1901210581.md
=> Add my test file in a new branch test

doc/Start/README.md
1. Add the index
2. Change the word linux to Linux
3. Change the word pr to PR in heading
=> Add the index and change the word linux to Linux

doc/HomeWork/1900022730.md
* 新建立了 doc/HomeWork/1900022730.md 
* 加入了第一周周报的内容
=> 1900022730 江姗姗 第一周周报

doc/HomeWork/1900022846.md
Submit the first weekly report from 10/20/2019 to 10/26/2019
=> Submit the first weekly report from 10/20/2019 to 10/26/2019

doc/HomeWork/1901210351.md
=> 提交了2019.10.20-2019.10.27第一周周报

doc/HomeWork/1900022708.md
=> /doc/HomeWork: Create homework file

doc/HomeWork/1901210736.md
=> 增加1901210736.md文件，记录10.20-10.27周报

doc/HomeWork/1901210694.md
=> 1901210694.md

doc/HomeWork/1901210447.md
刘嘉欣 1901210447 2019.10.20-2019.10.27第一周周报
=> 刘嘉欣 2019.10.20-2019.10.27周报

doc/HomeWork/1901210408.md
=> 1901210408_贾丽春_第一周周报

doc/HomeWork/1901210645.md
第一周周报。姓名什么的直接放上github不太好，就不打中文姓名了。
=> jiangyuzhao周报

doc/HomeWork/1901210401.md
写明2019年10月20日-2019年10月27日所做的工作
=> 1901210401-胡开阳-第一周周报

doc/HomeWork/1901210742
=> add 1901210742.md

doc/HomeWork/1901210756.md
=> 1901210756 第一周周报修改

doc/HomeWork/1900022784.md
=> 1900022784 黄佳威 第一周周报

doc/HomeWork/1901210454.md
在learn-with-open-source项目中提交了一个PR，修改了英文中的单复数错误和介词错误，https://github.com/zhuangbiaowei/learn-with-open-source/pull/196
参加了Kcoin区块链项目第一次组会
=> 1901210454刘珣的周报

doc/HomeWork/1901210388.md
=> 1901210388 戈通 第一周周报

doc/HomeWork/1901210625.md
提交戴启宇第一周周报，地址：doc/HomeWork/1901210625.md
=> 戴启宇1901210625第一周周报

doc/HomeWork/1901210514.md
1901210514王天佑2019.10.21-2019.10.27周报
=> 2019.10.21-2019.10.27周报

doc/HomeWork/1901210654.md
=> 1901210654.md

doc/HomeWork/1901210584.md
=> 张明轩1901210584提交7th周报告

doc/HomeWork/1900022730.md
按照周报格式 修改了doc/HomeWork/1900022730.md
=> 1900022730 江姗姗 第一周周报 按照要求进行了修改

doc/HomeWork/1901210675.md
=> doc/Homework: Create 1901210675.md

doc/HomeWork/1901210386.md
=> 19-10-21~27's list

doc/HomeWork/1901210724.md
=> work of this week

doc/HomeWork/1900022737.md
=> Submit the first weekly by Yifeng from 10/21/2019 to 10/27/2019

doc/HomeWork/1901210577.md
=> 1901210577.md

doc/HomeWork/1900022752.md
=> Creat 1900022752.md

doc/HomeWork/1901210782.md
=> 创建 1901210782.md

doc/HomeWork/1901210484.md
=> add 1901210484.md

doc/HomeWork/1901210405.md
=> 1901210405-黄乐一捷10.27周报

doc/Algorithms/快速排序.md, doc/HomeWork/1901210649.md
=> '添加快速排序.md'

doc/HomeWork/1900022720.md
=> updata week1 report

doc/HomeWork/1901210377.md
=> Add my homework file

doc/HomeWork/1901210729.md
=> 1901210729陆泽瑞 第一周周报 ：Add 1901210729.md

doc/HomeWork/1901210421.md
=> 李鼎1901210421

doc/HomeWork/1900022772.md
=> doc/HomeWork: 1900022772 周报

doc/HomeWork/1901210733.md
=> 周报-王冲1901210733

doc/HomeWork/DevUI/1900022754.md
1. 在zhuangbiaowei/learn-with-open-source项目中开始了一个PR，修改了错别字，但未点击create a pull request，提交失败；
2. 在zhuangbiaowei/learn-with-open-source项目中开始了一个PR，修改了语法问题，pr地址为：https://github.com/zhuangbiaowei/learn-with-open-source/pull/210#event-2746656465；
总结：本周掌握了Git基本命令的使用，熟悉了提交pr的流程。
=> 2019年10月20日-2019年10月27日 开源周报

doc/HomeWork/AICoder/1901210618.md
=> 1901210618.md

doc/HomeWork/AICoder/1901210536.md
=> 10月21日-27日周报

doc/HomeWork/AICoder/1901210275.md
=> this is a commit

doc/Algorithms/leetcode103.md
=> leetcode 103

doc/HomeWork/OSScan/1901210736.md
=> 增加10.27-11.03周报

doc/Algorithms/leetcode130.md, doc/HomeWork/OSScan/1901210420.md
之前提交的周报和其他内容在一个pr中，内容太多。所以，现在重新提交。
=> 周报-OSScan-20191026-20191031 

doc/HomeWork/KCoin/1901210657.md
=> 周报_Kcoin_20191028-20191031

doc/HomeWork/AICoder/1901210618.md
=> 周报-AI补全代码-20191028-20191103

doc/HomeWork/DevUI/1900022799.md
=> 周报-DevUI-2019.10.28-2019.10.31

doc/HomeWork/OSScan/1800022830.md
=> 开源组件健康扫描-第二周周报

doc/HomeWork/OSScan/1901210694.md
=> 周报-OSScan-10.27-11.03

doc/HomeWork/OSScan/1900022850.md
=> 周报_OSScan_2019.10.31

doc/HomeWork/OSScan/1901210351.md
=> 周报_OSScan_20191028

doc/HomeWork/OSScan/1900022773.md
=> 周报-OSScan-20191031

doc/HomeWork/KCoin/1901210389.md
=> kcoin 周报 龚俊琦

doc/GoLang/1900022750.md, doc/HomeWork/KCoin/1900022750.md
=> 周报_KCoin区块链小组_20191031

doc/HomeWork/KCoin/1901210560.md
=> 周报_KCoin区块链小组_10月31日

doc/HomeWork/KCoin/1901210698.md
Update 2019.10.27 - 2019.11.02
=> 周报-Kcoin-2019.10.31

doc/HomeWork/KCoin/1901210749.md
=> 周报更新-KCoin

doc/HomeWork/KCoin/1901210649.md
=> 周报_KCoin_20191027

doc/GoLang/1901210432_LeetCode 202&1122.md, doc/HomeWork/KCoin/1901210432.md
=> 周报_Kcoin_2019.10.28

doc/HomeWork/AICoder/1901210625.md
周报_AICoder_20191027-20191031_戴启宇
=> 周报_AICoder_20191027-20191031

doc/HomeWork/AICoder/1900022772.md
=> 周报-AICoder-1900022772

doc/HomeWork/AICoder/1901210401.md
=> 周报-AI代码补全-20191031-1901210401

doc/HomeWork/AICoder/1901210729.md
=> 周报-AI代码补全-20191028

doc/HomeWork/AICoder/1901210756.md
=> 第二周周报-AI代码补全-1901210756

doc/HomeWork/OSScan/1901210405.md
=> 周报_开源组件扫描_10.31

doc/GoLang/1901210782.md
=> 创建1901210782.md

doc/GoLang/1900022730.md
=> GoLang 学习笔记 1900022730 江姗姗

doc/GoLang/1901210556.md
=> code by go-yyl

doc/GoLang/1901210649.md
=> 更新go语言做的算法题

doc/GoLang/0408_20191102_Go语言学习报告.md
=> kcoin_1901210408_golang

doc/GoLang/1901210432.md
create 1901210432.md
1901210432 kcoin golang算法题
=> LeetCode算法题-Kcoin-2019.11.3

doc/HomeWork/OSScan/1900022844.md
=> OSScan-update 1900022844.md

doc/GoLang/1901210293golang.md
=> kcoin 算法 golang

doc/HomeWork/OSScan/1901210650.md
周报-OSScan-20191024-20191031 李娟
=> 周报-OSScan-20191024-20191031

doc/HomeWork/DevUI/1900022803.md
=> 周报_OSScan_20191103-20191107

doc/HomeWork/OSScan/1900022773.md
=> 周报_OSScan_11.1-11.7

doc/HomeWork/DevUI/1901210747.md
=> 周报_DevUI_20191028-20191107

doc/HomeWork/DevUI/1900022846.md
=> 周报_DevUI_20191027-20191031

doc/HomeWork/DevUI/1900022754(1).md
学习内容：
1. 学习了HTML教程、HTML5语义化标签、CSS教程、CSS盒子模型、CSS position属性。
2. 学习了前端中的JavaScript教程。
总结：了解了开源项目课程中关于HTML和CSS的知识点，学习了JavaScript的语法和使用方式。
=> 周报_DevUI_2019/10/28-2019/10/31

doc/HomeWork/OSScan/1900022720.md
1. git代码管理方式和协作方式
2. Git基本操作:git权威指南
=> 周报_OSScan_20191101-20191107

doc/HomeWork/KCoin/1901210389.md
=> 周报 kcoin 1901210389

doc/HomeWork/KCoin/1901210270.md
提交周报_Kcoin_1901210270_2019.11.01-2019.11.07
=> 周报_Kcoin_1901210270_2019.11.01-2019.11.07

doc/Algorithms/leetcode103.md, doc/Algorithms/leetcode130.md
为Algorithm中的leetcode题目添加C++Soultion
=> 为Algorithm中的leetcode题目添加C++Soultion

doc/HomeWork/AICoder/1901210694.md
=> 新加入组，将前两周的周报移动过来

doc/HomeWork/DevUI/1900022846.md
=> 周报_DevUI_20191108-20191114

doc/HomeWork/AICoder/1901210577.md
=> AICODER-1901210577-10.28-11.3.md

doc/HomeWork/AICoder/1901210625.md
戴启宇周报-AICoder-20191031-20191107
=> 周报-AICoder-20191031-20191107

doc/HomeWork/AICoder/1901210282.md
上周的周报没有被merge，就关闭了上周的pull request，两周的周报都提交到本周的pr里
=> 周报-AI代码补全-2019.11.8-11.14（以及11.7-13）

doc/HomeWork/KCoin/1901210782.md
提交 1901210782 2019-11-7~14 周报，
=> # Kcoin 提交 1901210782 2019-11-7~14 周报

doc/HomeWork/KCoin/review-report/1901210749.md
2019.11.8 - 2019.11.14代码review报告
=> Kcoin_代码Review报告_1901210749

doc/HomeWork/KCoin/1901210678.md
=> 周报_Kcoin_20191028-20191104

doc/HomeWork/KCoin/1901210782.md
增加2019-11-14~2019-11-21 工作内容总结
=> Kcoin 1901210782 周报更新.md

doc/HomeWork/KCoin/1800022815.md
=> Kcoin -更新本周报

doc/Fabric/1900022730-Hyperledger Fabric1.4 建立联盟链.md
=> kcoin-1900022730-提交新的fabric安装报告

doc/HomeWork/KCoin/1901210782.md
=> Kcoin 周报更新，1901210782.md

doc/HomeWork/KCoin/1901210782.md
=> Kcoin 2019-11-25~12-5 工作周报更新
